### PR TITLE
Tensorflow 2.0 conversion completed

### PR DESCRIPTION
**Pull request by SiliconForge**
As per instructions from the last pull request, i have fully converted the code to tensorflow 2, no compats used. I warn you to pull only the file with the tensorflow 2 code as i have kept the code from the last pull request on my fork so pulling it all will overwrite the good tensorflow 1 code.

### CODE REVIEW

**Comment by shakedzy** [comment]
Thanks a lot for your efforts! I'll take a look at this :)

**Comment by shakedzy** [comment]
Hi - it will be much easier (and safer) to merge if only the new file will be in this PR.

**Comment by SiliconForge** [comment]
Sorry, very new to this git thing, do i create a new fork with only the file or do i delete the file from my branch, commit the branch with only the new 2.0 file and do the PR again?

**Comment by shakedzy** [comment]
Either create an new PR  with only that file, or undo all changes in the other files on this PR. Do not delete them. because this will delete them from master if it merges.

**Comment by SiliconForge** [comment]
No idea how to make a PR of only one file, is there a way?

**Comment by SiliconForge** [comment]
Nevermind, i will delete the fork and create a new one in sync with the master and add the file.

**Pull request closed without merging**
